kind: Deployment
apiVersion: apps/v1
metadata:
  name: pt-max-station-vatno-worker
  namespace: maxstation-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pt-max-station-vatno-worker
  template:
    metadata:
      labels:
        app: pt-max-station-vatno-worker
    spec:
      containers:
        - name: pt-max-station-vatno-worker
          image: IMAGE_NAME
          resources:
           requests:
             memory: "64Mi"
             cpu: "250m"
           limits:
             memory: "500Mi"
             cpu: "500m"            
          # volumeMounts:
          # - name: azurefileshare
          #   mountPath: /app/AppLogs
          # - name: keyvaultshare
          #   mountPath: /app/Configs
          #   readOnly: false
          env:
          # - name: ConnectionFile
          #   value: /app/Configs/dev-maxstationconnection-db
          - name: APP_VERSION
            value: IMAGE_NAME
          - name: DOTNET_ENVIRONMENT
            value: Development
          # - name: ROOT_URL
          #   valueFrom:
          #     secretKeyRef:
          #       name: web-api-credentials
          #       key: dailyoperation_api
          - name: DB_ConnectionString
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: db_endpoint
          - name: ProductName
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: product_name
          - name: TZ
            value: "Asia/Bangkok"                 
          imagePullPolicy: Always            
      restartPolicy: Always
      imagePullSecrets:      
        - name: pt-max-station-registry-secret
      # volumes:
      #   - name: azurefileshare
      #     azureFile:
      #       secretName: storage-credentials
      #       shareName: api-dev
      #       readOnly: false
        # - name: keyvaultshare
        #   flexVolume:
        #     driver: "azure/kv"
        #     options:
        #       usevmmanagedidentity: "true"       
        #       vmmanagedidentityclientid: f348efb3-7769-4ebd-9e56-ef7ed0a86c75
        #       keyvaultname: ptgakskeyvault
        #       keyvaultobjectnames: dev-maxstationconnection-db
        #       keyvaultobjecttypes: secret               
        #       tenantid: 4675cb8a-c006-401b-8cd1-738a66cab301